version: '3'

services:
  localstack:
    container_name: local
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "4573:4573"
      - "4574:4574"
      - "4575:4575"
      - "8055:8080"
      - "4566:4566"
      - "4569:4569"
    environment:
      - SERVICES=dynamodb
      - TABLE_NAME=teste
      - ENDPOINT=http://localhost:4566
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "./aws:/etc/localstack/init/ready.d"



